### ISSUE TITLE
关于免费和开放的一点疑问

### ISSUE THREAD

**Issue by zxzllyj** [ovm-china/OVM#22]
直入主题，有以下几个疑问
第一：免费的如何盈利来保证后续开发
第二：开放是怎么个开放法
第三：后续是否会有开源版本
以上三个问题中第一个直接关系到是当做玩具还是直接采用，因为只有有盈利才会有后续的维护，不然作为基础设施无人维护又不是开源项目我相信无人放心使用；第二个问题是看到官网上说的开放，但是翻遍官网却没找到怎么个开放法，是开放源代码还是开放API，或者干脆开放的只是bug提交页？第三个问题是在问项目前景，开源固然失去一部分项目主导权和一部分闭源带来的商业利益，但是只有开源那些大佬才有可能参与这个项目，然后才有可能功能越来越多，项目越来越强大，最后成长为顶级项目。
ps：关注这个东西已经很久了，忍不住来问问，请勿见怪。
最后：开源只是一种精神，并不是一种义务，本issue只是询问，并无其他意义。

**Comment by chuxinweigai** [comment]
感谢关注 OVM已推出新版本 欢迎试用！
