### ISSUE TITLE
添加卷失败 500

### ISSUE THREAD

**Issue by pingandezhufu** [ovm-china/OVM#8]
![image](https://cloud.githubusercontent.com/assets/3054644/16068070/351ef204-32f5-11e6-927d-ae66ff6a4ef2.png)
在oa项目->硬盘,我点了+，显示以上错误，
数据中心，我添加了存储设备，如图所示
![image](https://cloud.githubusercontent.com/assets/3054644/16068115/bc96b7a8-32f5-11e6-857e-adaf1bd5c320.png)

**Comment by samyang2558** [comment]
存储池的名称应该为共享目录的路径，这个在正式版UI上会做控制
